# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Sudeste 2014"
email: "sudeste@devfest.com.br"
description: "Os melhores desenvolvedores Google presentes no maior evento de tecnologia da região Sudeste! Venha, aprenda, mostre seu valor e esteja no topo da comunidade!"
baseurl: "/zeppelin"
url: "http://sudeste.devfest.com.br"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Rio de Janeiro"
organizerAlternateName: "Google Developer Group Rio de Janeiro"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, sudeste"
twitterAccount: "@DevFestSe"
socialImageSrcGooglePlus: "/img/seo/meta-gp.png"
socialImageSrcTwitter: "/img/seo/meta-fb.png"
socialImageSrcFacebook: "/img/seo/meta-fb.png"

# Documents
c4pUrl: "http://bit.ly/DevFestSudeste-CallForPapers"
c4sponsorsUrl: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Palestrantes"}
 - {permalink: "/team/", text: "Equipe"}
 - {permalink: "/hackathon/", text: "Hackathon"}
 - {permalink: "/logistics/", text: "Como Chegar"}
#bottomNavigationLinks:
# - {link: "http://bit.ly/DevFestSudeste-CallForPapers", text: "Seja um palestrante"}
#rightNavigationButtons:
# - {link: "http://bit.ly/DevFestSudeste-CallForPapers", text: "Seja um palestrante"}

# Hero Block
heroImage: "RioHero.jpg"
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "8 de Novembro"
typeoutTextValues: '"", "Sudeste", "Rio de Janeiro", "Juiz de Fora", "Belo Horizonte", "Uberaba"'
typeoutFallback: "Sudeste"
heroButtons:
 - {permalink: "/#tickets", text: "Se inscreva"}
 #- {link: "http://bit.ly/DevFestSudeste-CallForPapers", text: "Seja um palestrante"}

# About Block
aboutTitle: "Sobre o GDG DevFest"
aboutBlock:
 - {title: "Conferência", image: "conference.jpg", text: "O maior evento do Sudeste relacionado ao Google cuidadosamente elaborado para você da comunidade GDG! Palestrantes impressionantes e muita diversão!" }
 - {title: "Palestras", image: "workshop.jpg", text: "Dia inteiro de palestras, Android, Chrome e Cloud. Venha domar a sua tecnologia favorita!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Dia inteiro de Hackathon! Quer trabalhar em equipe para criar um produto usando tecnologias Google? Junte seu time e participe!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "participantes", detail: "de todo Brasil"}
 - {count: "10", specialCharacter: "+", info: "horas", detail: "de tecnologias Google"}
 - {count: "10", specialCharacter: "+", info: "palestrantes", detail: ""}
 - {count: "2", specialCharacter: "", info: "eventos paralelos", detail: ""}

# Latest News Block
latestNewsTitle: "Últimas notícias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 1
rockstarSpeakersTitle: "Palestrantes Rockstar"
rockstarSpeakersButtonText: "Ver todos os palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Centro de Convenções Bolsa do Rio"
eventLocationLink: "http://www.noveeventos.com.br/pt-br/nossos-espacos/bolsa-do-rio.asp"
eventStreetAddress: "Praça XV de Novembro, 20"
eventAddressLocality: "Rio de Janeiro"
eventAddressLocalityRegion: "Rio de Janeiro"
eventPostalCode: "20010-010"
eventAddressCountry: "Brasil"
eventStartTime: "2014-11-08T09:00"
eventDoorTime: "08:30"
eventEndTime: "2014-10-25T18:30"
eventPlaceCoordinates: "-22.9070828, -43.181914800000015"
mapCenterCoordinates: "-22.9070828, -43.181914800000015"
mapMobileCenterCoordinates: "-22.9070828, -43.181914800000015"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Parceiros"
partnersC4sponsorsButton: "Seja um patrocinador"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Acompanhe as novidades"
subscribeAction: "http://emjuizdefora.us8.list-manage1.com/subscribe?u=54a5ee254093d994f8fe9af77&id=85ce972c0f"
subscribeInfo: "Cadastre-se e receba todas as novidades sobre o DevFest Sudeste!"

# Tickets Block
ticketsTitle: "Inscrições"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Palestras"
  price: "25"
  priceCurrency: "R$"
  ticketsNumber: "200"
  #ribbon: "-5%"
  buyButtonLink: "http://even.tc/devfest-sudeste-2014"
  buyButtonText: "Comprar"
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-11-07T23:59"
 -
  name: "Palestras + Hackathon"
  price: "35"
  priceCurrency: "R$"
  ticketsNumber: "100"
  #ribbon: "-20%"
  featured: true
  buyButtonLink: "http://even.tc/devfest-sudeste-2014"
  buyButtonText: "Comprar"
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-11-07T23:59"
  #disabled: true
 -
  name: "Hackathon"
  price: "25"
  priceCurrency: "R$"
  ticketsNumber: "100"
  buyButtonLink: "http://even.tc/devfest-sudeste-2014"
  buyButtonText: "Comprar"
  #additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  #soldOut: true
  #soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/115701636639101848032", icon: "google-plus"}
 - {link: "https://twitter.com/devfestse", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/DevFest-Sudeste/809735362381616", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://codigo-google.blogspot.com.br/", text: "Código Google"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contato"
  links:
   - {link: "mailto:sudeste@devfest.com.br", text: "Envie um email"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de conduta"}

# Blog
blogTitle: "Últimas notícias"
blogCommentsEnabled: true
discusShortName: "devfest-sudeste"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "Ferramentas e produtos do Google se tornaram sinônimo de produtividade e desempenho no mundo online. O número de inovações tecnológicas e indústrias de TI em que o Google está criando novas ferramentas e produtos é enorme. É difícil conhecer todos eles. É por isso que as pessoas começaram a se reunir em pequenos grupos locais e partilharam a sua experiência com tais produtos. Mais tarde, os seguintes grupos foram chamados Grupos de Desenvolvedores do Google. GDGs podem assumir muitas formas - de apenas algumas pessoas que se juntam para assistir alguns vídeos, para grandes encontros com demonstrações, palestras técnicas, hackathons e conferências."

# Logistics Find Way Block
findWayTitle: "Como chegar?"
findWayDistance: "Distância"
findWayDriving: "Carro"
findWayWalking: "Andando"
findWayBicycling: "Bicicleta"
findWayTransit: "Trânsito"
findWayFindFlight: "Encontrar um vôo"
logisticsMapCenterCoordinates: "-22.9070828, -43.181914800000015"
logisticsMapMobileCenterCoordinates: "-22.9070828, -43.181914800000015"

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Destaque-se na comunidade nacional de desenvolvedores"
hackathonRows:
 - {title: "#HackathonDevFest", image: "nerd-code.png", details: "Não basta estar lá, para muitos, é preciso também programar. Por isso criamos o hackathon do DevFest Sudeste; para você montar sua equipe, buscar uma ideia e partir para a implementação! Tudo isso em poucas horas e com uma premiação que realmente vale a pena! A única regra é desenvolver utilizando o Android e ter no máximo quatro membros na equipe."}
 - {title: "Android Wear", image: "hackathon-0.png", details: "Como expandir os limites com as novas possibilidades dos \"vestíveis\" em seus projetos? Nos surpreenda apresentando uma aplicação nova, de uma forma diferente ou apenas fazendo oque é óbvio mas ainda não foi feito."}
 - {title: "Google Glass", image: "hackathon-1.png", details: "Desenvolver para Google Glass não é para os fracos. Que tal utilizar o Glass Development Kit (GDK) para implementar com o Glass? A interface precisa ser adequada ao dispositivo bem como a interação deve ser cuidadosamente pensada. Ganhe pontos extras nesta competição desenvolvendo com a mais nova tecnologia!"}
 - {title: "Polymer", image: "Polymer.png", details: "Crie uma aplicação robusta e funcional em poucas horas utilizando Polymer, ou então crie seu próprio set de componentes. As ferramentas do Google para desenvolvedores são incríveis e utiliza-las em seus projetos nos enchem os olhos!"}
 - {title: "Chromecast", image: "prize-3.png", details: "E que tal utilizar o Chromecast como display para sua aplicação? Desde jogos até aplicações educacionais podem ser feitas utilizando-se do dispositivo. Destaque sua equipe implementando coisas inimagináveis com HTML5 e JavaScript! "}
 - {title: "Premiação", image: "relogio.png", details: "Chega de conversa! Todos os membros de sua equipe irão faturar um smartwatch LG GWatch, basta vencer a maratona! Esteja pronto para o desafio!"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Juízes"

# Hackathon Prizes Block
prizesTitle: "Premiação"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Localização"
hackathonLocationName: "Centro de Convenções Bolsa do Rio"
hackathonLocationLink: "http://www.noveeventos.com.br/pt-br/nossos-espacos/bolsa-do-rio.asp"
hackathonStreetAddress: "Praça XV de Novembro, 20"
hackathonAddressLocality: "Rio de Janeiro"
hackathonAddressLocalityRegion: "Rio de Janeiro"
hackathonPostalCode: "20010-010"
hackathonAddressCountry: "Brasil"
hackathonStartTime: "2014-11-08T09:00"
hackathonDoorTime: "08:30"
hackathonEndTime: "2014-10-25T18:30"
hackathonPlaceCoordinates: "-22.9070828, -43.181914800000015"
hackathonMapCenterCoordinates: "-22.9070828, -43.181914800000015"
hackathonMapMobileCenterCoordinates: "-22.9070828, -43.181914800000015"
